version: '3.8'

networks: 
  default-network:
    driver: bridge

services: 
  api:
    build:
      context: .
      dockerfile: build/api/Dockerfile
      target: dev
    ports: 
      - '3000:3000'
    volumes:
      - './api:/app/src'
    env_file: 
      - .env
    networks: 
      - default-network

  frontend:
    build: 
      context: .
      dockerfile: build/frontend/Dockerfile
      target: dev
    env_file: 
      - .env
    ports:
      - '3001:3001'
    volumes:
      - './frontend:/app'
    networks: 
      - default-network

  db-mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_PORT: $DB_PORT
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - '/var/lib/mysql'
    ports:
      - '3306:${DB_PORT}'
    networks: 
      - default-network
